### ISSUE TITLE
Confused - no directory as described

### ISSUE THREAD

**Issue by gmknowles** [Captain-Of-Coit/cs2-city-monitor#6]
This directory did no exist. I added it, but seems not to be working. A bit of help, please? 

* Directory - Cities2_Data\StreamingAssets\~UI~\HookUI\Extensions

**Comment by Woovie** [comment]
If you've installed BepinEx and HookUI successfully, you should see it loaded in the BepinEx console.

![image](https://github.com/Captain-Of-Coit/cs2-city-monitor/assets/7304619/05267fbe-5b1d-479a-85d1-c3d2cc709621)

That then creates the HookUI and Extensions folder at first time execution of the HookUI library.

**Comment by Captain-Of-Coit** [comment]
Yeah, you can either launch the game once, and it'll create the directory structure for you, or you can manually create the directory structure yourself, but it has to be exact, otherwise it won't work.

> Directory - Cities2_Data\StreamingAssets~UI~\HookUI\Extensions

Here there is a `\` missing between `StreamingAssets` and `~UI~`. 

The correct path is `Cities2_Data\StreamingAssets\~UI~\HookUI\Extensions`. I don't know if that was just a typo in the issue, but might be the reason it's not working.

**Comment by Captain-Of-Coit** [comment]
Please reopen/leave a comment if still a problem :)
